# Generated by Django 5.1.1 on 2024-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sattus', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('supplier', models.CharField(choices=[('Airlines ', 'Airlines '), ('Hotels ', 'Hotels '), ('Car rental companies', 'Car rental companies'), ('Travel insurance companies', 'Travel insurance companies'), ('Tour operators', 'Tour operators')], max_length=200, null=True)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
