# Generated by Django 5.1.1 on 2024-10-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_supply_product_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supply',
        ),
        migrations.AddField(
            model_name='product',
            name='purchased_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
