# Generated by Django 5.1.1 on 2024-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_product_supply_product_purchased_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Voyage Organizer', 'Voyage Organizer'), ('Omra', 'Omra'), ('Billetterie', 'Billetterie'), ('Voyage A La Cart', 'Voyage A La Cart'), ('Location Voiture', 'Location Voiture'), ('sejour linguistique', 'sejour linguistique')], max_length=200, null=True),
        ),
    ]
