# Generated by Django 5.1.1 on 2024-10-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sattus',
            new_name='status',
        ),
    ]
