# Generated by Django 5.1.1 on 2024-10-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(null=True),
        ),
    ]
