# Generated by Django 5.1.1 on 2024-10-03 07:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_order_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(null=True, verbose_name=accounts.models.Customer),
        ),
    ]
