# Generated by Django 5.1.1 on 2024-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_order_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
