# Generated by Django 5.1.1 on 2024-10-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_date_created',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_num',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
