# Generated by Django 5.1.1 on 2024-10-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customer_passport_date_created_customer_passport_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passport_num',
            new_name='passport_number',
        ),
    ]
